### ISSUE TITLE
Unable to import module 'lib/index': Error

### ISSUE THREAD

**Issue by happynaut** [bespoken/streamer#19]
After I've deployed the tool and set it up in Lambda, I get an error in the log files:

`Unable to import module 'lib/index': Error
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/var/task/lib/index.js:4:15)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)`

**Comment by jkelvie** [comment]
Hi happynaut, how did you deploy it? The most common issue is that the file needs to be archived from the top-level directory, so the file structure of the archive looks like this:
/lib
/node_modules
/package.json

Is that how your directory is structured? More deployment info is here:
https://github.com/bespoken/streamer/blob/master/README_DEPLOY.md

Hope that helps - let me know.

**Comment by happynaut** [comment]
Hi jkelvie, 

Thanks for the prompt feedback. It seems that actually I am doing something wrong :(
I'm using your deployment info but just zipped the whole project and uploaded the zip.

**Comment by jkelvie** [comment]
Is it working now?

-John

**Comment by happynaut** [comment]
Nope. I just downloaded all files from github and create a zip of it.

**Comment by jkelvie** [comment]
Hi, did you run npm install on it? That will create the node_modules directory that is necessary to use the streamer.

**Comment by happynaut** [comment]
My mistake. I've overseen this. Thanks so much for the support.

**Comment by jkelvie** [comment]
Happy to help, and glad to hear it is sorted out!
