### ISSUE TITLE
Not seeing Alexa triggers in Lambda

### ISSUE THREAD

**Issue by deskpops** [bespoken/streamer#20]
Hi,

Thanks for providing this! I'm trying to test a deployment. All instructions worked fine until I got to setting up Lambda.

I zipped and uploaded the project to Lambda, but there are no Alexa options in Lambda I can find. I downloaded NPM and put the node_modules in /lib and added package.json. 

When zipped, the package comes to 14MB which is says is "too large for inline editing."

Any help would be appreciated.

Thanks,
Jeff

**Comment by alexaguy** [comment]
Never mind. I found my issue

**Comment by deskpops** [comment]
Never mind. I saw my problem.
